import { Sidebar } from '@/components/layout';
import { Providers } from '@/store/Providers';
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import React from 'react';
import './globals.css';

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  style: ['normal', 'italic'],
  weight: ['300', '400', '500', '600', '700']
});

export const metadata: Metadata = {
  title: 'Todo App by Karp',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body
        className={`${poppins.className} container flex bg-light text-dark`}
      >
        <Sidebar />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
