import { Providers } from '@/store/Providers';
import './globals.css';
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import { Sidebar } from '@/components/layout';

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  style: ['normal', 'italic'],
  weight: ['300', '400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Todo App by Karp',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body
        className={`${poppins.className} flex container text-dark bg-light`}
      >
        <Sidebar />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
